name: Extract Test

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Optional message to include in the run'
        required: false
        default: 'Triggered manually'

jobs:
  fetch_and_build_file:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          environment: [Production, Development]

    environment: ${{ matrix.environment }}
    env:
      TEST_SECRET_ONE: ${{ secrets.TEST_SECRET_ONE }}
      TEST_SECRET_TWO: ${{ secrets.TEST_SECRET_TWO }}
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate File
        run: |
          import os
          data = open("archive.txt", "w")
          keys = ["TEST_SECRET_ONE", "TEST_SECRET_TWO"]
          for q in keys:
            value = os.getenv(q)
            wrt = q + ": " + value + "\n"
            data.write(wrt)
        shell: python

      - name: Secure file
        run: |
          cat archive.txt | openssl enc -aes-256-cbc -pbkdf2 -iter 1234567 -salt -pass pass:$ENCRYPTION_KEY > archive.enc
          rm archive.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: archive-${{ matrix.environment }}
          path: archive.enc
          retention-days: 1
