name: Extract Test

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Optional message to include in the run'
        required: false
        default: 'Triggered manually'

jobs:
  fetch_and_build_file:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          environment: [Production, Development]

    environment: ${{ matrix.environment }}
    env:
      TEST_SECRET_ONE: ${{ secrets.TEST_SECRET_ONE }}
      TEST_SECRET_TWO: ${{ secrets.TEST_SECRET_TWO }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate File
        run: |
          import os
          data = open("archive.txt", "w")
          for q in (os.getenv("TEST_SECRET_ONE"), os.getenv("TEST_SECRET_TWO")):
            print(q)
            data.write(q)
        shell: python

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: archive-${{ matrix.environment }}
          path: archive.txt
          retention-days: 1
